import { useEffect } from 'react'

export type Language = 'system' | 'ru' | 'en' | 'es' | 'de' | 'fr' | 'pt' | 'it' | 'zh' | 'ja'
export const languageNames: Record<Language, string> = { system:'Системный язык', ru:'Русский', en:'English', es:'Español', de:'Deutsch', fr:'Français', pt:'Português', it:'Italiano', zh:'简体中文', ja:'日本語' }
export function systemLanguage(): Exclude<Language, 'system'> { const l = (navigator.language || 'en').toLowerCase(); if (l.startsWith('ru')) return 'ru'; if (l.startsWith('es')) return 'es'; if (l.startsWith('de')) return 'de'; if (l.startsWith('fr')) return 'fr'; if (l.startsWith('pt')) return 'pt'; if (l.startsWith('it')) return 'it'; if (l.startsWith('zh')) return 'zh'; if (l.startsWith('ja')) return 'ja'; return 'en' }

const en: Record<string,string> = {
  'Браузеры для выбора':'Browsers in the picker','Соберите только нужные сочетания браузеров и профилей.':'Keep only the browser and profile combinations you need.','Добавить':'Add','Указать путь':'Choose path','Обновить браузеры':'Refresh browsers','Отмена':'Cancel','Добавьте браузер или профиль для окна выбора.':'Add a browser or profile to the picker.',
  'Всегда открывать этот сайт в выбранном браузере':'Always open this site in the selected browser',
  'Основные':'General','Браузеры':'Browsers','Правила':'Rules','Оформление':'Appearance','О приложении':'About','Помощь и поддержка':'Help & support','Помощь':'Help','НАСТРОЙКИ':'SETTINGS',
  'Picklink работает':'Picklink is running','Ссылки под контролем':'Links under control','Сделайте Picklink основным для ссылок':'Make Picklink your link handler','После этого при клике на ссылку появится выбор браузера и профиля.':'Then every link will show the browser and profile picker.','Подключить':'Connect','Изменить':'Change','Picklink уже открывает ваши ссылки':'Picklink already handles your links','Обработчик HTTPS подключён.':'HTTPS handler is connected.','Обработчики HTTP и HTTPS подключены.':'HTTP and HTTPS handlers are connected.',
  'Поведение ссылок':'Link behavior','Решите, что делать с новыми ссылками.':'Choose what happens with new links.','Когда я открываю ссылку':'When I open a link','Picklink покажет аккуратное окно выбора браузера.':'Picklink will show a browser picker.','Всегда спрашивать':'Always ask','БЫСТРАЯ ПРОВЕРКА':'QUICK TEST','Посмотрите, как будет выглядеть выбор':'Preview the browser picker','Проверить ссылку':'Test a link','Система':'System','Запускать вместе с Windows':'Launch at sign-in','Picklink будет готов сразу после входа в систему.':'Picklink will be ready after sign-in.','Показывать адрес сайта':'Show website address','Отображать домен в окне выбора браузера.':'Show the domain in the picker.','Ваши ссылки остаются приватными':'Your links stay private','Все правила обрабатываются локально на этом компьютере.':'All rules are processed locally.',
  'Доступные браузеры':'Available browsers','Список формируется из зарегистрированных в системе приложений.':'Built from apps registered on this device.','Профиль':'Profile','Основной':'Default','Клавиша':'Key','Активен':'Active','Обновить список':'Refresh list','Быстрый выбор с клавиатуры':'Quick keyboard selection','Любая буква или цифра':'Any letter or number','Назначьте каждой строке удобную клавишу. Esc закрывает окно выбора.':'Assign a convenient key to each row. Esc closes the picker.','Назначьте клавишу и профиль для каждого браузера. Esc закрывает окно.':'Assign a key and profile to each browser. Esc closes the picker.','Готов к использованию':'Ready to use',
  'Ссылки сами найдут нужный браузер':'Links find the right browser automatically','Создавайте правила для сайтов, рабочих сервисов и отдельных профилей.':'Create rules for websites, work services and profiles.','Ваши правила':'Your rules','Адрес содержит':'Address contains','Новое правило':'New rule',
  'Тема приложения':'App theme','Системная тема меняется автоматически вместе с оформлением устройства.':'System theme follows your device automatically.','Системная · тёмная':'System · dark','Системная · светлая':'System · light','Светлая':'Light','Тёмная':'Dark','Язык интерфейса':'Interface language','Выберите язык приложения.':'Choose the app language.',
  'Каждой ссылке — свой браузер.':'The right browser for every link.','О проекте':'About the project','Приватно и локально':'Private and local','Быстрое и понятное управление ссылками без отправки данных.':'Fast link control without sending your data.','Автор проекта':'Created by','Дизайн, идея и разработка приложения.':'Design, concept and development.',
  'Как пользоваться Picklink':'How to use Picklink','Три коротких шага, чтобы ссылки открывались именно там, где нужно.':'Three quick steps to open links exactly where you want.','Начало работы':'Getting started','Подключите Picklink':'Connect Picklink','На вкладке «Основные» нажмите «Подключить» и назначьте Picklink для HTTP и HTTPS.':'On General, click Connect and assign Picklink to HTTP and HTTPS.','Проверьте браузеры':'Check browsers','На вкладке «Браузеры» обновите список, выберите профиль и назначьте клавишу.':'On Browsers, refresh the list, select a profile and assign a key.','Открывайте ссылки':'Open links','Выберите браузер мышью или нажмите его клавишу. Esc закрывает окно выбора.':'Choose a browser with the mouse or its key. Esc closes the picker.','Если что-то не найдено':'If something is missing','Обновите системную регистрацию браузера':'Refresh browser registration','Откройте нужный браузер, временно назначьте его браузером по умолчанию, затем вернитесь в Picklink и нажмите «Обновить список». Это заставит браузер заново добавить себя в реестр приложений.':'Open the browser you need, temporarily set it as the default browser, then return to Picklink and click Refresh browsers. This makes the browser register itself in Windows again.','Открыть ссылку':'Open link','Основной профиль':'Default profile','Системный язык':'System language','Версия':'Version'
}

const dictionaries: Record<Exclude<Language, 'system'>,Record<string,string>> = {
  ru:{}, en,
  es:{...en,'Основные':'General','Браузеры':'Navegadores','Правила':'Reglas','Оформление':'Apariencia','О приложении':'Acerca de','Помощь и поддержка':'Ayuda y soporte','Помощь':'Ayuda','НАСТРОЙКИ':'AJUSTES','Подключить':'Conectar','Поведение ссылок':'Comportamiento de enlaces','Всегда спрашивать':'Preguntar siempre','Система':'Sistema','Доступные браузеры':'Navegadores disponibles','Профиль':'Perfil','Основной':'Predeterminado','Клавиша':'Tecla','Активен':'Activo','Обновить список':'Actualizar lista','Тема приложения':'Tema de la aplicación','Светлая':'Claro','Тёмная':'Oscuro','Язык интерфейса':'Idioma de la interfaz','Выберите язык приложения.':'Elige el idioma de la aplicación.','О проекте':'Sobre el proyecto','Автор проекта':'Creado por','Начало работы':'Primeros pasos','Системный язык':'Idioma del sistema','Версия':'Versión','Откройте нужный браузер, временно назначьте его браузером по умолчанию, затем вернитесь в Picklink и нажмите «Обновить список». Это заставит браузер заново добавить себя в реестр приложений.':'Abre el navegador necesario, configúralo temporalmente como predeterminado, vuelve a Picklink y pulsa Actualizar navegadores. Así el navegador se registrará de nuevo en Windows.'},
  de:{...en,'Основные':'Allgemein','Браузеры':'Browser','Правила':'Regeln','Оформление':'Darstellung','О приложении':'Über die App','Помощь и поддержка':'Hilfe & Support','Помощь':'Hilfe','НАСТРОЙКИ':'EINSTELLUNGEN','Подключить':'Verbinden','Поведение ссылок':'Linkverhalten','Всегда спрашивать':'Immer fragen','Система':'System','Доступные браузеры':'Verfügbare Browser','Профиль':'Profil','Основной':'Standard','Клавиша':'Taste','Активен':'Aktiv','Обновить список':'Liste aktualisieren','Тема приложения':'App-Design','Светлая':'Hell','Тёмная':'Dunkel','Язык интерфейса':'Sprache','Выберите язык приложения.':'Wähle die Sprache der App.','О проекте':'Über das Projekt','Автор проекта':'Erstellt von','Начало работы':'Erste Schritte','Системный язык':'Systemsprache','Версия':'Version','Откройте нужный браузер, временно назначьте его браузером по умолчанию, затем вернитесь в Picklink и нажмите «Обновить список». Это заставит браузер заново добавить себя в реестр приложений.':'Öffne den gewünschten Browser, lege ihn vorübergehend als Standardbrowser fest, kehre zu Picklink zurück und klicke auf Browser aktualisieren. Dadurch registriert sich der Browser erneut in Windows.'},
  fr:{...en,'Основные':'Général','Браузеры':'Navigateurs','Правила':'Règles','Оформление':'Apparence','О приложении':'À propos','Помощь и поддержка':'Aide et support','Помощь':'Aide','НАСТРОЙКИ':'RÉGLAGES','Подключить':'Connecter','Поведение ссылок':'Comportement des liens','Всегда спрашивать':'Toujours demander','Система':'Système','Доступные браузеры':'Navigateurs disponibles','Профиль':'Profil','Основной':'Par défaut','Клавиша':'Touche','Активен':'Actif','Обновить список':'Actualiser','Тема приложения':'Thème de l’application','Светлая':'Clair','Тёмная':'Sombre','Язык интерфейса':'Langue','Выберите язык приложения.':'Choisissez la langue de l’application.','О проекте':'À propos du projet','Автор проекта':'Créé par','Начало работы':'Bien démarrer','Системный язык':'Langue du système','Версия':'Version','Откройте нужный браузер, временно назначьте его браузером по умолчанию, затем вернитесь в Picklink и нажмите «Обновить список». Это заставит браузер заново добавить себя в реестр приложений.':'Ouvrez le navigateur souhaité, définissez-le temporairement par défaut, revenez dans Picklink et cliquez sur Actualiser les navigateurs. Le navigateur se réenregistrera ainsi dans Windows.'},
  pt:{...en,'Основные':'Geral','Браузеры':'Navegadores','Правила':'Regras','Оформление':'Aparência','О приложении':'Sobre','Помощь и поддержка':'Ajuda e suporte','Помощь':'Ajuda','НАСТРОЙКИ':'CONFIGURAÇÕES','Подключить':'Conectar','Поведение ссылок':'Comportamento dos links','Всегда спрашивать':'Sempre perguntar','Система':'Sistema','Доступные браузеры':'Navegadores disponíveis','Профиль':'Perfil','Основной':'Padrão','Клавиша':'Tecla','Активен':'Ativo','Обновить список':'Atualizar lista','Тема приложения':'Tema do aplicativo','Светлая':'Claro','Тёмная':'Escuro','Язык интерфейса':'Idioma','Выберите язык приложения.':'Escolha o idioma do aplicativo.','О проекте':'Sobre o projeto','Автор проекта':'Criado por','Начало работы':'Primeiros passos','Системный язык':'Idioma do sistema','Версия':'Versão','Откройте нужный браузер, временно назначьте его браузером по умолчанию, затем вернитесь в Picklink и нажмите «Обновить список». Это заставит браузер заново добавить себя в реестр приложений.':'Abra o navegador desejado, defina-o temporariamente como padrão, volte ao Picklink e clique em Atualizar navegadores. Isso fará o navegador se registrar novamente no Windows.'},
  it:{...en,'Основные':'Generali','Браузеры':'Browser','Правила':'Regole','Оформление':'Aspetto','О приложении':'Informazioni','Помощь и поддержка':'Aiuto e supporto','Помощь':'Aiuto','НАСТРОЙКИ':'IMPOSTAZIONI','Подключить':'Collega','Поведение ссылок':'Comportamento dei link','Всегда спрашивать':'Chiedi sempre','Система':'Sistema','Доступные браузеры':'Browser disponibili','Профиль':'Profilo','Основной':'Predefinito','Клавиша':'Tasto','Активен':'Attivo','Обновить список':'Aggiorna elenco','Тема приложения':'Tema dell’app','Светлая':'Chiaro','Тёмная':'Scuro','Язык интерфейса':'Lingua','Выберите язык приложения.':'Scegli la lingua dell’app.','О проекте':'Informazioni sul progetto','Автор проекта':'Creato da','Начало работы':'Per iniziare','Системный язык':'Lingua di sistema','Версия':'Versione','Откройте нужный браузер, временно назначьте его браузером по умолчанию, затем вернитесь в Picklink и нажмите «Обновить список». Это заставит браузер заново добавить себя в реестр приложений.':'Apri il browser desiderato, impostalo temporaneamente come predefinito, torna in Picklink e fai clic su Aggiorna browser. In questo modo il browser si registrerà nuovamente in Windows.'},
  zh:{...en,'Основные':'常规','Браузеры':'浏览器','Правила':'规则','Оформление':'外观','О приложении':'关于','Помощь и поддержка':'帮助与支持','Помощь':'帮助','НАСТРОЙКИ':'设置','Подключить':'连接','Поведение ссылок':'链接行为','Всегда спрашивать':'始终询问','Система':'系统','Доступные браузеры':'可用浏览器','Профиль':'配置文件','Основной':'默认','Клавиша':'按键','Активен':'已启用','Обновить список':'刷新列表','Тема приложения':'应用主题','Светлая':'浅色','Тёмная':'深色','Язык интерфейса':'界面语言','Выберите язык приложения.':'选择应用语言。','О проекте':'关于项目','Автор проекта':'创作者','Начало работы':'开始使用','Системный язык':'系统语言','Версия':'版本','Откройте нужный браузер, временно назначьте его браузером по умолчанию, затем вернитесь в Picklink и нажмите «Обновить список». Это заставит браузер заново добавить себя в реестр приложений.':'打开所需的浏览器，暂时将其设为默认浏览器，然后返回 Picklink 并点击“刷新浏览器”。这会让浏览器重新注册到 Windows。'},
  ja:{...en,'Основные':'一般','Браузеры':'ブラウザー','Правила':'ルール','Оформление':'外観','О приложении':'このアプリについて','Помощь и поддержка':'ヘルプとサポート','Помощь':'ヘルプ','НАСТРОЙКИ':'設定','Подключить':'接続','Поведение ссылок':'リンクの動作','Всегда спрашивать':'常に確認','Система':'システム','Доступные браузеры':'利用可能なブラウザー','Профиль':'プロファイル','Основной':'デフォルト','Клавиша':'キー','Активен':'有効','Обновить список':'一覧を更新','Тема приложения':'アプリのテーマ','Светлая':'ライト','Тёмная':'ダーク','Язык интерфейса':'表示言語','Выберите язык приложения.':'アプリの言語を選択します。','О проекте':'プロジェクトについて','Автор проекта':'制作者','Начало работы':'はじめに','Системный язык':'システム言語','Версия':'バージョン','Откройте нужный браузер, временно назначьте его браузером по умолчанию, затем вернитесь в Picklink и нажмите «Обновить список». Это заставит браузер заново добавить себя в реестр приложений.':'使用するブラウザーを開いて一時的に既定のブラウザーに設定し、Picklink に戻って「ブラウザーを更新」をクリックしてください。これによりブラウザーが Windows に再登録されます。'}
}

const originals = new WeakMap<Text,string>()
function translateText(node: Text, language: Exclude<Language, 'system'>) {
  const raw = originals.get(node) ?? node.data
  if (!originals.has(node)) originals.set(node, raw)
  const translated = dictionaries[language][raw.trim()]
  const target = translated ? `${raw.match(/^\s*/)?.[0] || ''}${translated}${raw.match(/\s*$/)?.[0] || ''}` : raw
  if (node.data !== target) node.data = target
}
function translate(root: Node, language: Exclude<Language, 'system'>) {
  if (root.nodeType === Node.TEXT_NODE) return translateText(root as Text, language)
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT)
  let node: Text | null
  while ((node = walker.nextNode() as Text | null)) translateText(node, language)
}
export function useLocalization(language: Language) {
  useEffect(() => {
    const effective = language === 'system' ? systemLanguage() : language
    document.documentElement.lang = effective
    translate(document.body, effective)
    const translatedValues = new Set(Object.values(dictionaries[effective]))
    const observer = new MutationObserver(items => items.forEach(item => {
      if (item.type === 'characterData') {
        const node = item.target as Text
        if (!translatedValues.has(node.data.trim())) { originals.set(node, node.data); translateText(node, effective) }
      } else item.addedNodes.forEach(node => translate(node, effective))
    }))
    observer.observe(document.body, { childList:true, characterData:true, subtree:true })
    return () => observer.disconnect()
  }, [language])
}
